services:
    sql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password@1
        ports:
            - 1433:1433
        volumes:
            - sql-data:/var/opt/mssql

volumes:
    sql-data:
